[pytest]
addopts = -p no:cacheprovider
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::PendingDeprecationWarning:starlette.formparsers
    ignore::SyntaxWarning:sentence_transformers.*