name: CD - Deploy H&M App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 30m
          script: |
            set -e
            cd /home/ubuntu/hm-fashion-recommender

            echo "📥 Fetching latest code..."
            git pull origin main

            echo "🛠️ Ensuring Docker Compose V2..."
            curl -SL https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64 -o ./docker-compose
            chmod +x ./docker-compose

            echo "🧹 Cleaning up OLD containers (Fixing Conflicts)..."
            ./docker-compose down --remove-orphans || true

            echo "🚀 Starting Deployment (This might be slow ONLY ONCE)..."
            ./docker-compose up -d --build

            echo "✨ Cleaning up dangling images..."
            docker image prune -f