name: CD - Deploy to K3s (AWS)

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 10m
          command_timeout: 30m
          script: |
            # 1. Go to the folder and catch the errors.
            set -e
            cd /home/ubuntu/hm-fashion-recommender
            
            # 2. Check the latest code
            echo "Pulling latest code..."
            git pull origin main
            
            # 3. Rebuild Docker images.
            echo "Building Docker images..."
            make k8s-build
            
            # 4. Import images into K3s.
            echo "Importing images to K3s..."
            docker save hm-backend:latest | sudo k3s ctr images import -
            docker save hm-frontend:latest | sudo k3s ctr images import -
            
            # 5. Restart Pods (Rollout)
            echo "Restarting Kubernetes Deployments..."
            sudo kubectl rollout restart deployment backend
            sudo kubectl rollout restart deployment frontend
            
            echo "Deployment Successful!"